service: example-service

plugins:
  - serverless-mongodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}

custom:
  mongodb:
    instance:
      dbName: MyDB

functions:
